- name: copy_files_handler
  copy:
    src: "{{ item }}" 
    dest: /var/www/html/
  loop: "{{ files_name }}"


- name: copy_template_handler
  template:
    src: "{{ template_file }}"
    dest: /var/www/html/index.html


- name: Restart_package_handler
  systemd:
    name: "{{ package_name }}"
    state: started

